

# Android
ABI=x86
#ABI=arm64-v8a
ANDROID_VER:=26
ANDROID_BUILDTOOLS:=26.0.2
ANDROID_KEYSTORE:=/Users/reuben/.android/debug.keystore
ANDROID_KEYSTORE_PASSWORD:=android
ANDROID_KEY_PASSWORD:=android
ANDROID_KEY_ALIAS:=androiddebugkey

# iOS
IOS_SDK=iPhoneOS11.1.sdk
IOS_ABIS=arm64
IOS_CERT=AA35BF8660055BE507571702777D49D2609620E9
IOS_PROVISIONING_PROFILE=/Users/reuben/Library/MobileDevice/Provisioning\ Profiles/8973664a-c5d7-4972-92d9-9c9a1990499e.mobileprovision

# macOS
MACOS_SDK=MacOSX10.13.sdk

# Should be provided by environment variables
ANDROID_SDK_DIR:=/Users/reuben/Library/Android/sdk

include $(OAKNUT_DIR)/oaknut.make

