

# Android
ABI=x86
#ABI=arm64-v8a
ANDROID_VER:=26
ANDROID_BUILDTOOLS:=26.0.2
ANDROID_KEYSTORE:=/Users/reuben/.android/debug.keystore
ANDROID_KEYSTORE_PASSWORD:=android
ANDROID_KEY_PASSWORD:=android
ANDROID_KEY_ALIAS:=androiddebugkey

# iOS
IOS_SDK=iPhoneOS11.1.sdk
IOS_ABIS=arm64
IOS_CERT=D1FCEAF1B5FF0C2588E461648C0488ECFEA10161
IOS_PROVISIONING_PROFILE=/Users/reuben/Library/MobileDevice/Provisioning\ Profiles/2e47ce16-3a69-42d0-ae59-c25992b7dcaa.mobileprovision

# macOS
MACOS_SDK=MacOSX10.13.sdk

# Should be provided by environment variables
ANDROID_SDK_DIR:=/Users/reuben/Library/Android/sdk
EMSCRIPTEN_DIR:=/Users/reuben/Downloads/emsdk-portable/emscripten/1.37.22

include $(OAKNUT_DIR)/oaknut.make

