PROJECT_NAME=ListView

# Include the Oaknut makefile
OAKNUT_DIR:=$(wildcard $(OAKNUT_DIR))
ifndef OAKNUT_DIR
$(error OAKNUT_DIR must point to the Oaknut root)
endif
include $(OAKNUT_DIR)/build/oaknut.make
